/*jslint vars: true, plusplus: true, devel: true, nomen: true, regexp: true, indent: 4, maxerr: 50 */
/*global $, Folder*/


function SplitText(){
psd = app.activeDocument;
layer = psd.activeLayer;
var text = layer.textItem.contents;
var textArray = text.split("\r");
var lngth = textArray.length+1;
for (var w=1; w<lngth;w++){
    wordlayer = layer.duplicate();
    wordlayer.name = textArray[w-1];
    wordlayer.textItem.contents = textArray[w-1];
    psd.activeLayer = wordlayer;

}
layer.remove();
}





function ubahThanks(value){
var doc = app.activeDocument;
var docName = doc.name;
docName = docName.match(/(.*)(\.[^\.]+)/) ? docName = docName.match(/(.*)(\.[^\.]+)/):docName = [docName, docName];
createFolder(doc.path+"/"+docName[1]);
for(i=value;i<30;i++){
	
	if(i>20){
		var x = i-20;
		if(x<1){
		var finalval = "1M++"; 
		}else{
		var finalval = "1."+x+"M++";
		}
	}else{
		var finalval = i*50+"K++";
	}
	changeText(finalval,docName[1]);
}




}

function simpanJpeg(){
	var doc = app.activeDocument;	
	var docName = doc.name;

docName = docName.match(/(.*)(\.[^\.]+)/) ? docName = docName.match(/(.*)(\.[^\.]+)/):docName = [docName, docName];

	var file = new File(doc.path+"/"+docName[1]+".jpg");
	var opts = new JPEGSaveOptions();
	opts.quality=10;
	doc.saveAs(file,opts,true);		
}

function createFolder(value){
	var file = new Folder(value);
	file.create();
}


function changeText(text,dname){
var g = app.activeDocument.layerSets.getByName('thanks');
var c = g.layers[0];
c.textItem.contents=text;
saveJpeg(dname+"/"+dname+"_"+text);    

}

function saveJpeg(dname){
var doc = app.activeDocument;
	
	var file = new File(doc.path+"/"+dname+".jpg");
	var opts = new JPEGSaveOptions();
	opts.quality=10;
	doc.saveAs(file,opts,true);	
	//doc.close(SaveOptions.YES);
}


function dropShadow(){
	var layer = app.activeDocument.layerSets.getByName('ds').layers[0];
	layer.textItem.contents="Helcclo";
}
function changeColorMul(){
	var myColor = getColorpickerColor(); 

if (myColor !== false){
	var r = myColor.rgb.red;
	var g = myColor.rgb.green;
	var b = myColor.rgb.blue;


	var desc6 = new ActionDescriptor();
    var ref1 = new ActionReference();
    ref1.putProperty(charIDToTypeID('Prpr'), charIDToTypeID('Lefx'));
    ref1.putEnumerated(charIDToTypeID('Lyr '), charIDToTypeID('Ordn'), charIDToTypeID('Trgt'));
    desc6.putReference(charIDToTypeID('null'), ref1);
    var desc7 = new ActionDescriptor();
    var desc8 = new ActionDescriptor();
    desc8.putBoolean(charIDToTypeID('enab'), true);
    desc8.putBoolean(stringIDToTypeID('present'), true);
    desc8.putBoolean(stringIDToTypeID('showInDialog'), true);
    desc8.putEnumerated(charIDToTypeID('Md  '), charIDToTypeID('BlnM'), charIDToTypeID('Mltp'));//Nrml
    var desc9 = new ActionDescriptor();
    desc9.putDouble(charIDToTypeID('Rd  '), r);
    desc9.putDouble(charIDToTypeID('Grn '), g);
    desc9.putDouble(charIDToTypeID('Bl  '), b);
    desc8.putObject(charIDToTypeID('Clr '), charIDToTypeID('RGBC'), desc9);
    desc8.putUnitDouble(charIDToTypeID('Opct'), charIDToTypeID('#Prc'), 100.000000);
    desc7.putObject(charIDToTypeID('SoFi'), charIDToTypeID('SoFi'), desc8);
    desc6.putObject(charIDToTypeID('T   '), charIDToTypeID('Lefx'), desc7);
    executeAction(charIDToTypeID('setd'), desc6, DialogModes.NO);
}

function getColorpickerColor()
{
    if (app.showColorPicker())
    {
        return app.foregroundColor
    }
    else
    {
        return false
    }
}; // end of getColor()
}
function changeColor(){
	var myColor = getColorpickerColor(); 

if (myColor !== false){
	var r = myColor.rgb.red;
	var g = myColor.rgb.green;
	var b = myColor.rgb.blue;


	var desc6 = new ActionDescriptor();
    var ref1 = new ActionReference();
    ref1.putProperty(charIDToTypeID('Prpr'), charIDToTypeID('Lefx'));
    ref1.putEnumerated(charIDToTypeID('Lyr '), charIDToTypeID('Ordn'), charIDToTypeID('Trgt'));
    desc6.putReference(charIDToTypeID('null'), ref1);
    var desc7 = new ActionDescriptor();
    var desc8 = new ActionDescriptor();
    desc8.putBoolean(charIDToTypeID('enab'), true);
    desc8.putBoolean(stringIDToTypeID('present'), true);
    desc8.putBoolean(stringIDToTypeID('showInDialog'), true);
    desc8.putEnumerated(charIDToTypeID('Md  '), charIDToTypeID('BlnM'), charIDToTypeID('Nrml'));//Nrml
    var desc9 = new ActionDescriptor();
    desc9.putDouble(charIDToTypeID('Rd  '), r);
    desc9.putDouble(charIDToTypeID('Grn '), g);
    desc9.putDouble(charIDToTypeID('Bl  '), b);
    desc8.putObject(charIDToTypeID('Clr '), charIDToTypeID('RGBC'), desc9);
    desc8.putUnitDouble(charIDToTypeID('Opct'), charIDToTypeID('#Prc'), 100.000000);
    desc7.putObject(charIDToTypeID('SoFi'), charIDToTypeID('SoFi'), desc8);
    desc6.putObject(charIDToTypeID('T   '), charIDToTypeID('Lefx'), desc7);
    executeAction(charIDToTypeID('setd'), desc6, DialogModes.NO);
}

function getColorpickerColor()
{
    if (app.showColorPicker())
    {
        return app.foregroundColor
    }
    else
    {
        return false
    }
}; // end of getColor()
}

function changeText(textx){
	alert(textx);
	executeAction(stringIDToTypeID("placedLayerEditContents")); 
	var text = app.activeDocument.layers.getByName("text");
	activeDocument.activeLayer.textItem.contents=textx;
app.activeDocument.save();
app.activeDocument.close();
// var l = app.activeDocument.layers.getByName("tes");
// app.activeDocument.activeLayer = l;
// executeAction(stringIDToTypeID("placedLayerEditContents")); 
// var text = app.activeDocument.layers.getByName("text");
// app.activeDocument.activeLayer = text;
// executeAction(stringIDToTypeID("placedLayerEditContents")); 
// activeDocument.activeLayer = activeDocument.artLayers.getByName("text");

// activeDocument.activeLayer.textItem.contents=textx;
// app.activeDocument.save();
// app.activeDocument.close();
// app.activeDocument.save();
// app.activeDocument.close();
}

function doEdit(tes,isitalic,fntsize){

    var randomname = makeid(5);
    function makeid(length) {
        var result           = '';
        var characters       = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
        var charactersLength = characters.length;
        for ( var i = 0; i < length; i++ ) {
           result += characters.charAt(Math.floor(Math.random() * charactersLength));
        }
        return result;
     }
    // =======================================================
    var idsetd = charIDToTypeID( "setd" );
    var desc9813 = new ActionDescriptor();
    var idnull = charIDToTypeID( "null" );
        var ref1229 = new ActionReference();
        var idLyr = charIDToTypeID( "Lyr " );
        var idOrdn = charIDToTypeID( "Ordn" );
        var idTrgt = charIDToTypeID( "Trgt" );
        ref1229.putEnumerated( idLyr, idOrdn, idTrgt );
    desc9813.putReference( idnull, ref1229 );
    var idT = charIDToTypeID( "T   " );
        var desc9814 = new ActionDescriptor();
        var idNm = charIDToTypeID( "Nm  " );
        desc9814.putString( idNm, randomname );
    var idLyr = charIDToTypeID( "Lyr " );
    desc9813.putObject( idT, idLyr, desc9814 );
    executeAction( idsetd, desc9813, DialogModes.NO );
    var idplacedLayerConvertToLayers = stringIDToTypeID( "placedLayerConvertToLayers" );
    executeAction( idplacedLayerConvertToLayers, undefined, DialogModes.NO );
    
    // =======================================================
    var idslct = charIDToTypeID( "slct" );
        var desc9778 = new ActionDescriptor();
        var idnull = charIDToTypeID( "null" );
            var ref1203 = new ActionReference();
            var idLyr = charIDToTypeID( "Lyr " );
            ref1203.putName( idLyr, "txt" );
        desc9778.putReference( idnull, ref1203 );
        var idMkVs = charIDToTypeID( "MkVs" );
        desc9778.putBoolean( idMkVs, false );
        var idLyrI = charIDToTypeID( "LyrI" );
            var list749 = new ActionList();
            list749.putInteger( 114 );
        desc9778.putList( idLyrI, list749 );
    executeAction( idslct, desc9778, DialogModes.NO );
    
    // =======================================================
    var idsetd = charIDToTypeID( "setd" );
        var desc9779 = new ActionDescriptor();
        var idnull = charIDToTypeID( "null" );
            var ref1204 = new ActionReference();
            var idPrpr = charIDToTypeID( "Prpr" );
            var idTxtS = charIDToTypeID( "TxtS" );
            ref1204.putProperty( idPrpr, idTxtS );
            var idTxLr = charIDToTypeID( "TxLr" );
            var idOrdn = charIDToTypeID( "Ordn" );
            var idTrgt = charIDToTypeID( "Trgt" );
            ref1204.putEnumerated( idTxLr, idOrdn, idTrgt );
        desc9779.putReference( idnull, ref1204 );
        var idT = charIDToTypeID( "T   " );
            var desc9780 = new ActionDescriptor();
            var idtextOverrideFeatureName = stringIDToTypeID( "textOverrideFeatureName" );
            desc9780.putInteger( idtextOverrideFeatureName, 808465458 );
            var idtypeStyleOperationType = stringIDToTypeID( "typeStyleOperationType" );
            desc9780.putInteger( idtypeStyleOperationType, 3 );
            var idSz = charIDToTypeID( "Sz  " );
            var idPnt = charIDToTypeID( "#Pnt" );
            desc9780.putUnitDouble( idSz, idPnt, fntsize );
        var idTxtS = charIDToTypeID( "TxtS" );
        desc9779.putObject( idT, idTxtS, desc9780 );
    executeAction( idsetd, desc9779, DialogModes.NO );
    
    // =======================================================
    var idsetd = charIDToTypeID( "setd" );
        var desc9781 = new ActionDescriptor();
        var idnull = charIDToTypeID( "null" );
            var ref1205 = new ActionReference();
            var idPrpr = charIDToTypeID( "Prpr" );
            var idTxtS = charIDToTypeID( "TxtS" );
            ref1205.putProperty( idPrpr, idTxtS );
            var idTxLr = charIDToTypeID( "TxLr" );
            var idOrdn = charIDToTypeID( "Ordn" );
            var idTrgt = charIDToTypeID( "Trgt" );
            ref1205.putEnumerated( idTxLr, idOrdn, idTrgt );
        desc9781.putReference( idnull, ref1205 );
        var idT = charIDToTypeID( "T   " );
            var desc9782 = new ActionDescriptor();
            var idtextOverrideFeatureName = stringIDToTypeID( "textOverrideFeatureName" );
            desc9782.putInteger( idtextOverrideFeatureName, 808465460 );
            var idtypeStyleOperationType = stringIDToTypeID( "typeStyleOperationType" );
            desc9782.putInteger( idtypeStyleOperationType, 3 );
            var idsyntheticItalic = stringIDToTypeID( "syntheticItalic" );
            desc9782.putBoolean( idsyntheticItalic, isitalic );
        var idTxtS = charIDToTypeID( "TxtS" );
        desc9781.putObject( idT, idTxtS, desc9782 );
    executeAction( idsetd, desc9781, DialogModes.NO );
    
    // =======================================================
    var idslct = charIDToTypeID( "slct" );
        var desc9783 = new ActionDescriptor();
        var idnull = charIDToTypeID( "null" );
            var ref1206 = new ActionReference();
            var idLyr = charIDToTypeID( "Lyr " );
            ref1206.putName( idLyr, randomname);
        desc9783.putReference( idnull, ref1206 );
        var idMkVs = charIDToTypeID( "MkVs" );
        desc9783.putBoolean( idMkVs, false );
        var idLyrI = charIDToTypeID( "LyrI" );
            var list750 = new ActionList();
            list750.putInteger( 115 );
        desc9783.putList( idLyrI, list750 );
    executeAction( idslct, desc9783, DialogModes.NO );
    

    
    // =======================================================
    var idnewPlacedLayer = stringIDToTypeID( "newPlacedLayer" );
    executeAction( idnewPlacedLayer, undefined, DialogModes.NO );
    


}

function doShit(tes,isitalic,fntsize){

    var myColor = getColorpickerColor();
    if (myColor !== false){
        var r = myColor.rgb.red;
        var g = myColor.rgb.green;
        var b = myColor.rgb.blue;
        doText(tes,r,g,b,isitalic,fntsize);
    }
    function getColorpickerColor()
{
    if (app.showColorPicker())
    {
        return app.foregroundColor
    }
    else
    {
        return false
    }
}; // end of getColor()
    
}

function doText(tes,r,g,b,isitalic,fntsize){
    var fntsize = fntsize;
    var italicme = isitalic;
    var idMk = charIDToTypeID( "Mk  " );
    var desc363 = new ActionDescriptor();
    var idnull = charIDToTypeID( "null" );
        var ref54 = new ActionReference();
        var idTxLr = charIDToTypeID( "TxLr" );
        ref54.putClass( idTxLr );
    desc363.putReference( idnull, ref54 );
    var idUsng = charIDToTypeID( "Usng" );
        var desc364 = new ActionDescriptor();
        var idTxt = charIDToTypeID( "Txt " );
        desc364.putString( idTxt, tes );
        var idwarp = stringIDToTypeID( "warp" );
            var desc365 = new ActionDescriptor();
            var idwarpStyle = stringIDToTypeID( "warpStyle" );
            var idwarpStyle = stringIDToTypeID( "warpStyle" );
            var idwarpNone = stringIDToTypeID( "warpNone" );
            desc365.putEnumerated( idwarpStyle, idwarpStyle, idwarpNone );
            var idwarpValue = stringIDToTypeID( "warpValue" );
            desc365.putDouble( idwarpValue, 0.000000 );
            var idwarpPerspective = stringIDToTypeID( "warpPerspective" );
            desc365.putDouble( idwarpPerspective, 0.000000 );
            var idwarpPerspectiveOther = stringIDToTypeID( "warpPerspectiveOther" );
            desc365.putDouble( idwarpPerspectiveOther, 0.000000 );
            var idwarpRotate = stringIDToTypeID( "warpRotate" );
            var idOrnt = charIDToTypeID( "Ornt" );
            var idHrzn = charIDToTypeID( "Hrzn" );
            desc365.putEnumerated( idwarpRotate, idOrnt, idHrzn );
        var idwarp = stringIDToTypeID( "warp" );
        desc364.putObject( idwarp, idwarp, desc365 );
        var idTxtC = charIDToTypeID( "TxtC" );
            var desc366 = new ActionDescriptor();
            var idHrzn = charIDToTypeID( "Hrzn" );
            var idPrc = charIDToTypeID( "#Prc" );
            desc366.putUnitDouble( idHrzn, idPrc, 17.835366 );
            var idVrtc = charIDToTypeID( "Vrtc" );
            var idPrc = charIDToTypeID( "#Prc" );
            desc366.putUnitDouble( idVrtc, idPrc, 21.680217 );
        var idPnt = charIDToTypeID( "Pnt " );
        desc364.putObject( idTxtC, idPnt, desc366 );
        var idtextGridding = stringIDToTypeID( "textGridding" );
        var idtextGridding = stringIDToTypeID( "textGridding" );
        var idNone = charIDToTypeID( "None" );
        desc364.putEnumerated( idtextGridding, idtextGridding, idNone );
        var idOrnt = charIDToTypeID( "Ornt" );
        var idOrnt = charIDToTypeID( "Ornt" );
        var idHrzn = charIDToTypeID( "Hrzn" );
        desc364.putEnumerated( idOrnt, idOrnt, idHrzn );
        var idAntA = charIDToTypeID( "AntA" );
        var idAnnt = charIDToTypeID( "Annt" );
        var idantiAliasSharp = stringIDToTypeID( "antiAliasSharp" );
        desc364.putEnumerated( idAntA, idAnnt, idantiAliasSharp );
        var idbounds = stringIDToTypeID( "bounds" );
            var desc367 = new ActionDescriptor();
            var idLeft = charIDToTypeID( "Left" );
            var idPnt = charIDToTypeID( "#Pnt" );
            desc367.putUnitDouble( idLeft, idPnt, 0.000000 );
            var idTop = charIDToTypeID( "Top " );
            var idPnt = charIDToTypeID( "#Pnt" );
            desc367.putUnitDouble( idTop, idPnt, -23.057693 );
            var idRght = charIDToTypeID( "Rght" );
            var idPnt = charIDToTypeID( "#Pnt" );
            desc367.putUnitDouble( idRght, idPnt, 249.738262 );
            var idBtom = charIDToTypeID( "Btom" );
            var idPnt = charIDToTypeID( "#Pnt" );
            desc367.putUnitDouble( idBtom, idPnt, 6.857941 );
        var idbounds = stringIDToTypeID( "bounds" );
        desc364.putObject( idbounds, idbounds, desc367 );
        var idboundingBox = stringIDToTypeID( "boundingBox" );
            var desc368 = new ActionDescriptor();
            var idLeft = charIDToTypeID( "Left" );
            var idPnt = charIDToTypeID( "#Pnt" );
            desc368.putUnitDouble( idLeft, idPnt, 1.454996 );
            var idTop = charIDToTypeID( "Top " );
            var idPnt = charIDToTypeID( "#Pnt" );
            desc368.putUnitDouble( idTop, idPnt, -19.384431 );
            var idRght = charIDToTypeID( "Rght" );
            var idPnt = charIDToTypeID( "#Pnt" );
            desc368.putUnitDouble( idRght, idPnt, 148.892666 );
            var idBtom = charIDToTypeID( "Btom" );
            var idPnt = charIDToTypeID( "#Pnt" );
            desc368.putUnitDouble( idBtom, idPnt, 0.241439 );
        var idboundingBox = stringIDToTypeID( "boundingBox" );
        desc364.putObject( idboundingBox, idboundingBox, desc368 );
        var idtextShape = stringIDToTypeID( "textShape" );
            var list55 = new ActionList();
                var desc369 = new ActionDescriptor();
                var idTEXT = charIDToTypeID( "TEXT" );
                var idTEXT = charIDToTypeID( "TEXT" );
                var idPnt = charIDToTypeID( "Pnt " );
                desc369.putEnumerated( idTEXT, idTEXT, idPnt );
                var idOrnt = charIDToTypeID( "Ornt" );
                var idOrnt = charIDToTypeID( "Ornt" );
                var idHrzn = charIDToTypeID( "Hrzn" );
                desc369.putEnumerated( idOrnt, idOrnt, idHrzn );
                var idTrnf = charIDToTypeID( "Trnf" );
                    var desc370 = new ActionDescriptor();
                    var idxx = stringIDToTypeID( "xx" );
                    desc370.putDouble( idxx, 1.000000 );
                    var idxy = stringIDToTypeID( "xy" );
                    desc370.putDouble( idxy, 0.000000 );
                    var idyx = stringIDToTypeID( "yx" );
                    desc370.putDouble( idyx, 0.000000 );
                    var idyy = stringIDToTypeID( "yy" );
                    desc370.putDouble( idyy, 1.000000 );
                    var idtx = stringIDToTypeID( "tx" );
                    desc370.putDouble( idtx, 0.000000 );
                    var idty = stringIDToTypeID( "ty" );
                    desc370.putDouble( idty, 0.000000 );
                var idTrnf = charIDToTypeID( "Trnf" );
                desc369.putObject( idTrnf, idTrnf, desc370 );
                var idrowCount = stringIDToTypeID( "rowCount" );
                desc369.putInteger( idrowCount, 1 );
                var idcolumnCount = stringIDToTypeID( "columnCount" );
                desc369.putInteger( idcolumnCount, 1 );
                var idrowMajorOrder = stringIDToTypeID( "rowMajorOrder" );
                desc369.putBoolean( idrowMajorOrder, true );
                var idrowGutter = stringIDToTypeID( "rowGutter" );
                var idPnt = charIDToTypeID( "#Pnt" );
                desc369.putUnitDouble( idrowGutter, idPnt, 0.000000 );
                var idcolumnGutter = stringIDToTypeID( "columnGutter" );
                var idPnt = charIDToTypeID( "#Pnt" );
                desc369.putUnitDouble( idcolumnGutter, idPnt, 0.000000 );
                var idSpcn = charIDToTypeID( "Spcn" );
                var idPnt = charIDToTypeID( "#Pnt" );
                desc369.putUnitDouble( idSpcn, idPnt, 0.000000 );
                var idframeBaselineAlignment = stringIDToTypeID( "frameBaselineAlignment" );
                var idframeBaselineAlignment = stringIDToTypeID( "frameBaselineAlignment" );
                var idalignByAscent = stringIDToTypeID( "alignByAscent" );
                desc369.putEnumerated( idframeBaselineAlignment, idframeBaselineAlignment, idalignByAscent );
                var idfirstBaselineMinimum = stringIDToTypeID( "firstBaselineMinimum" );
                var idPnt = charIDToTypeID( "#Pnt" );
                desc369.putUnitDouble( idfirstBaselineMinimum, idPnt, 0.000000 );
                var idbase = stringIDToTypeID( "base" );
                    var desc371 = new ActionDescriptor();
                    var idHrzn = charIDToTypeID( "Hrzn" );
                    desc371.putDouble( idHrzn, 0.000000 );
                    var idVrtc = charIDToTypeID( "Vrtc" );
                    desc371.putDouble( idVrtc, 0.000000 );
                var idPnt = charIDToTypeID( "Pnt " );
                desc369.putObject( idbase, idPnt, desc371 );
            var idtextShape = stringIDToTypeID( "textShape" );
            list55.putObject( idtextShape, desc369 );
        desc364.putList( idtextShape, list55 );
        var idTxtt = charIDToTypeID( "Txtt" );
            var list56 = new ActionList();
                var desc372 = new ActionDescriptor();
                var idFrom = charIDToTypeID( "From" );
                desc372.putInteger( idFrom, 0 );
                var idT = charIDToTypeID( "T   " );
                desc372.putInteger( idT, 50 );
                var idTxtS = charIDToTypeID( "TxtS" );
                    var desc373 = new ActionDescriptor();
                    var idstyleSheetHasParent = stringIDToTypeID( "styleSheetHasParent" );
                    desc373.putBoolean( idstyleSheetHasParent, true );
                    var idfontPostScriptName = stringIDToTypeID( "fontPostScriptName" );
                    desc373.putString( idfontPostScriptName, """UniSansHeavyCAPS""" );
                    var idFntN = charIDToTypeID( "FntN" );
                    desc373.putString( idFntN, """Uni Sans""" );
                    var idFntS = charIDToTypeID( "FntS" );
                    desc373.putString( idFntS, """Heavy CAPS""" );
                    var idScrp = charIDToTypeID( "Scrp" );
                    desc373.putInteger( idScrp, 0 );
                    var idFntT = charIDToTypeID( "FntT" );
                    desc373.putInteger( idFntT, 0 );
                    var idfontAvailable = stringIDToTypeID( "fontAvailable" );
                    desc373.putBoolean( idfontAvailable, true );
                    var idSz = charIDToTypeID( "Sz  " );
                    var idPnt = charIDToTypeID( "#Pnt" );
                    desc373.putUnitDouble( idSz, idPnt, fntsize );
                    var idimpliedFontSize = stringIDToTypeID( "impliedFontSize" );
                    var idPnt = charIDToTypeID( "#Pnt" );
                    desc373.putUnitDouble( idimpliedFontSize, idPnt, fntsize );
                    var idHrzS = charIDToTypeID( "HrzS" );
                    desc373.putDouble( idHrzS, 100.000000 );
                    var idVrtS = charIDToTypeID( "VrtS" );
                    desc373.putDouble( idVrtS, 100.000000 );
                    var idsyntheticBold = stringIDToTypeID( "syntheticBold" );
                    desc373.putBoolean( idsyntheticBold, true );
                    var idsyntheticItalic = stringIDToTypeID( "syntheticItalic" );
                    desc373.putBoolean( idsyntheticItalic, italicme );
                    var idautoLeading = stringIDToTypeID( "autoLeading" );
                    desc373.putBoolean( idautoLeading, false );
                    var idLdng = charIDToTypeID( "Ldng" );
                    var idPnt = charIDToTypeID( "#Pnt" );
                    desc373.putUnitDouble( idLdng, idPnt, 6.763149 );
                    var idimpliedLeading = stringIDToTypeID( "impliedLeading" );
                    var idPnt = charIDToTypeID( "#Pnt" );
                    desc373.putUnitDouble( idimpliedLeading, idPnt, 6.763149 );
                    var idTrck = charIDToTypeID( "Trck" );
                    desc373.putInteger( idTrck, -60 );
                    var idBsln = charIDToTypeID( "Bsln" );
                    var idPnt = charIDToTypeID( "#Pnt" );
                    desc373.putUnitDouble( idBsln, idPnt, 0.000000 );
                    var idimpliedBaselineShift = stringIDToTypeID( "impliedBaselineShift" );
                    var idPnt = charIDToTypeID( "#Pnt" );
                    desc373.putUnitDouble( idimpliedBaselineShift, idPnt, 0.000000 );
                    var idfontCaps = stringIDToTypeID( "fontCaps" );
                    var idfontCaps = stringIDToTypeID( "fontCaps" );
                    var idNrml = charIDToTypeID( "Nrml" );
                    desc373.putEnumerated( idfontCaps, idfontCaps, idNrml );
                    var iddigitSet = stringIDToTypeID( "digitSet" );
                    var iddigitSet = stringIDToTypeID( "digitSet" );
                    var idarabicDigits = stringIDToTypeID( "arabicDigits" );
                    desc373.putEnumerated( iddigitSet, iddigitSet, idarabicDigits );
                    var idkashidas = stringIDToTypeID( "kashidas" );
                    var idkashidas = stringIDToTypeID( "kashidas" );
                    var idkashidaDefault = stringIDToTypeID( "kashidaDefault" );
                    desc373.putEnumerated( idkashidas, idkashidas, idkashidaDefault );
                    var iddiacXOffset = stringIDToTypeID( "diacXOffset" );
                    var idPnt = charIDToTypeID( "#Pnt" );
                    desc373.putUnitDouble( iddiacXOffset, idPnt, 0.000000 );
                    var iddiacYOffset = stringIDToTypeID( "diacYOffset" );
                    var idPnt = charIDToTypeID( "#Pnt" );
                    desc373.putUnitDouble( iddiacYOffset, idPnt, 0.000000 );
                    var idmarkYDistFromBaseline = stringIDToTypeID( "markYDistFromBaseline" );
                    var idPnt = charIDToTypeID( "#Pnt" );
                    desc373.putUnitDouble( idmarkYDistFromBaseline, idPnt, 0.000000 );
                    var idbaseline = stringIDToTypeID( "baseline" );
                    var idbaseline = stringIDToTypeID( "baseline" );
                    var idNrml = charIDToTypeID( "Nrml" );
                    desc373.putEnumerated( idbaseline, idbaseline, idNrml );
                    var idotbaseline = stringIDToTypeID( "otbaseline" );
                    var idotbaseline = stringIDToTypeID( "otbaseline" );
                    var idNrml = charIDToTypeID( "Nrml" );
                    desc373.putEnumerated( idotbaseline, idotbaseline, idNrml );
                    var idstrikethrough = stringIDToTypeID( "strikethrough" );
                    var idstrikethrough = stringIDToTypeID( "strikethrough" );
                    var idstrikethroughOff = stringIDToTypeID( "strikethroughOff" );
                    desc373.putEnumerated( idstrikethrough, idstrikethrough, idstrikethroughOff );
                    var idUndl = charIDToTypeID( "Undl" );
                    var idUndl = charIDToTypeID( "Undl" );
                    var idunderlineOff = stringIDToTypeID( "underlineOff" );
                    desc373.putEnumerated( idUndl, idUndl, idunderlineOff );
                    var idligature = stringIDToTypeID( "ligature" );
                    desc373.putBoolean( idligature, true );
                    var idaltligature = stringIDToTypeID( "altligature" );
                    desc373.putBoolean( idaltligature, false );
                    var idcontextualLigatures = stringIDToTypeID( "contextualLigatures" );
                    desc373.putBoolean( idcontextualLigatures, true );
                    var idfractions = stringIDToTypeID( "fractions" );
                    desc373.putBoolean( idfractions, false );
                    var idordinals = stringIDToTypeID( "ordinals" );
                    desc373.putBoolean( idordinals, false );
                    var idswash = stringIDToTypeID( "swash" );
                    desc373.putBoolean( idswash, false );
                    var idtitling = stringIDToTypeID( "titling" );
                    desc373.putBoolean( idtitling, false );
                    var idconnectionForms = stringIDToTypeID( "connectionForms" );
                    desc373.putBoolean( idconnectionForms, false );
                    var idstylisticAlternates = stringIDToTypeID( "stylisticAlternates" );
                    desc373.putBoolean( idstylisticAlternates, false );
                    var idstylisticSets = stringIDToTypeID( "stylisticSets" );
                    desc373.putInteger( idstylisticSets, 0 );
                    var idornaments = stringIDToTypeID( "ornaments" );
                    desc373.putBoolean( idornaments, false );
                    var idjustificationAlternates = stringIDToTypeID( "justificationAlternates" );
                    desc373.putBoolean( idjustificationAlternates, false );
                    var idfigureStyle = stringIDToTypeID( "figureStyle" );
                    var idfigureStyle = stringIDToTypeID( "figureStyle" );
                    var idNrml = charIDToTypeID( "Nrml" );
                    desc373.putEnumerated( idfigureStyle, idfigureStyle, idNrml );
                    var idproportionalMetrics = stringIDToTypeID( "proportionalMetrics" );
                    desc373.putBoolean( idproportionalMetrics, false );
                    var idkana = stringIDToTypeID( "kana" );
                    desc373.putBoolean( idkana, false );
                    var iditalics = stringIDToTypeID( "italics" );
                    desc373.putBoolean( iditalics, false );
                    var idbaselineDirection = stringIDToTypeID( "baselineDirection" );
                    var idbaselineDirection = stringIDToTypeID( "baselineDirection" );
                    var idwithStream = stringIDToTypeID( "withStream" );
                    desc373.putEnumerated( idbaselineDirection, idbaselineDirection, idwithStream );
                    var idtextLanguage = stringIDToTypeID( "textLanguage" );
                    var idtextLanguage = stringIDToTypeID( "textLanguage" );
                    var idenglishLanguage = stringIDToTypeID( "englishLanguage" );
                    desc373.putEnumerated( idtextLanguage, idtextLanguage, idenglishLanguage );
                    var idjapaneseAlternate = stringIDToTypeID( "japaneseAlternate" );
                    var idjapaneseAlternate = stringIDToTypeID( "japaneseAlternate" );
                    var iddefaultForm = stringIDToTypeID( "defaultForm" );
                    desc373.putEnumerated( idjapaneseAlternate, idjapaneseAlternate, iddefaultForm );
                    var idmojiZume = stringIDToTypeID( "mojiZume" );
                    desc373.putDouble( idmojiZume, 0.000000 );
                    var idgridAlignment = stringIDToTypeID( "gridAlignment" );
                    var idgridAlignment = stringIDToTypeID( "gridAlignment" );
                    var idroman = stringIDToTypeID( "roman" );
                    desc373.putEnumerated( idgridAlignment, idgridAlignment, idroman );
                    var idnoBreak = stringIDToTypeID( "noBreak" );
                    desc373.putBoolean( idnoBreak, false );
                    var idClr = charIDToTypeID( "Clr " );
                        var desc374 = new ActionDescriptor();
                        //ganti warna
                        var idRd = charIDToTypeID( "Rd  " );
                        desc374.putDouble( idRd, r );
                        var idGrn = charIDToTypeID( "Grn " );
                        desc374.putDouble( idGrn, g );
                        var idBl = charIDToTypeID( "Bl  " );
                        desc374.putDouble( idBl, b );
                    var idRGBC = charIDToTypeID( "RGBC" );
                    desc373.putObject( idClr, idRGBC, desc374 );
                    var idstrokeColor = stringIDToTypeID( "strokeColor" );
                        var desc375 = new ActionDescriptor();
                        var idRd = charIDToTypeID( "Rd  " );
                        desc375.putDouble( idRd, 0.000000 );
                        var idGrn = charIDToTypeID( "Grn " );
                        desc375.putDouble( idGrn, 0.000000 );
                        var idBl = charIDToTypeID( "Bl  " );
                        desc375.putDouble( idBl, 0.000000 );
                    var idRGBC = charIDToTypeID( "RGBC" );
                    desc373.putObject( idstrokeColor, idRGBC, desc375 );
                    var idbaseParentStyle = stringIDToTypeID( "baseParentStyle" );
                        var desc376 = new ActionDescriptor();
                        var idfontPostScriptName = stringIDToTypeID( "fontPostScriptName" );
                        desc376.putString( idfontPostScriptName, """MyriadPro-Regular""" );
                        var idFntN = charIDToTypeID( "FntN" );
                        desc376.putString( idFntN, """Myriad Pro""" );
                        var idFntS = charIDToTypeID( "FntS" );
                        desc376.putString( idFntS, """Regular""" );
                        var idScrp = charIDToTypeID( "Scrp" );
                        desc376.putInteger( idScrp, 0 );
                        var idFntT = charIDToTypeID( "FntT" );
                        desc376.putInteger( idFntT, 0 );
                        var idfontAvailable = stringIDToTypeID( "fontAvailable" );
                        desc376.putBoolean( idfontAvailable, true );
                        var idSz = charIDToTypeID( "Sz  " );
                        var idPnt = charIDToTypeID( "#Pnt" );
                        desc376.putUnitDouble( idSz, idPnt, 12.000000 );
                        var idimpliedFontSize = stringIDToTypeID( "impliedFontSize" );
                        var idPnt = charIDToTypeID( "#Pnt" );
                        desc376.putUnitDouble( idimpliedFontSize, idPnt, 12.000000 );
                        var idHrzS = charIDToTypeID( "HrzS" );
                        desc376.putDouble( idHrzS, 100.000000 );
                        var idVrtS = charIDToTypeID( "VrtS" );
                        desc376.putDouble( idVrtS, 100.000000 );
                        var idsyntheticBold = stringIDToTypeID( "syntheticBold" );
                        desc376.putBoolean( idsyntheticBold, false );
                        var idsyntheticItalic = stringIDToTypeID( "syntheticItalic" );
                        desc376.putBoolean( idsyntheticItalic, false );
                        var idautoLeading = stringIDToTypeID( "autoLeading" );
                        desc376.putBoolean( idautoLeading, true );
                        var idTrck = charIDToTypeID( "Trck" );
                        desc376.putInteger( idTrck, 0 );
                        var idBsln = charIDToTypeID( "Bsln" );
                        var idPnt = charIDToTypeID( "#Pnt" );
                        desc376.putUnitDouble( idBsln, idPnt, 0.000000 );
                        var idimpliedBaselineShift = stringIDToTypeID( "impliedBaselineShift" );
                        var idPnt = charIDToTypeID( "#Pnt" );
                        desc376.putUnitDouble( idimpliedBaselineShift, idPnt, 0.000000 );
                        var idcharacterRotation = stringIDToTypeID( "characterRotation" );
                        desc376.putDouble( idcharacterRotation, 0.000000 );
                        var idAtKr = charIDToTypeID( "AtKr" );
                        var idAtKr = charIDToTypeID( "AtKr" );
                        var idmetricsKern = stringIDToTypeID( "metricsKern" );
                        desc376.putEnumerated( idAtKr, idAtKr, idmetricsKern );
                        var idfontCaps = stringIDToTypeID( "fontCaps" );
                        var idfontCaps = stringIDToTypeID( "fontCaps" );
                        var idNrml = charIDToTypeID( "Nrml" );
                        desc376.putEnumerated( idfontCaps, idfontCaps, idNrml );
                        var iddigitSet = stringIDToTypeID( "digitSet" );
                        var iddigitSet = stringIDToTypeID( "digitSet" );
                        var iddefaultDigits = stringIDToTypeID( "defaultDigits" );
                        desc376.putEnumerated( iddigitSet, iddigitSet, iddefaultDigits );
                        var iddirOverride = stringIDToTypeID( "dirOverride" );
                        var iddirOverride = stringIDToTypeID( "dirOverride" );
                        var iddirOverrideDefault = stringIDToTypeID( "dirOverrideDefault" );
                        desc376.putEnumerated( iddirOverride, iddirOverride, iddirOverrideDefault );
                        var idkashidas = stringIDToTypeID( "kashidas" );
                        var idkashidas = stringIDToTypeID( "kashidas" );
                        var idkashidaDefault = stringIDToTypeID( "kashidaDefault" );
                        desc376.putEnumerated( idkashidas, idkashidas, idkashidaDefault );
                        var iddiacVPos = stringIDToTypeID( "diacVPos" );
                        var iddiacVPos = stringIDToTypeID( "diacVPos" );
                        var iddiacVPosOpenType = stringIDToTypeID( "diacVPosOpenType" );
                        desc376.putEnumerated( iddiacVPos, iddiacVPos, iddiacVPosOpenType );
                        var iddiacXOffset = stringIDToTypeID( "diacXOffset" );
                        var idPnt = charIDToTypeID( "#Pnt" );
                        desc376.putUnitDouble( iddiacXOffset, idPnt, 0.000000 );
                        var iddiacYOffset = stringIDToTypeID( "diacYOffset" );
                        var idPnt = charIDToTypeID( "#Pnt" );
                        desc376.putUnitDouble( iddiacYOffset, idPnt, 0.000000 );
                        var idmarkYDistFromBaseline = stringIDToTypeID( "markYDistFromBaseline" );
                        var idPnt = charIDToTypeID( "#Pnt" );
                        desc376.putUnitDouble( idmarkYDistFromBaseline, idPnt, 100.000000 );
                        var idbaseline = stringIDToTypeID( "baseline" );
                        var idbaseline = stringIDToTypeID( "baseline" );
                        var idNrml = charIDToTypeID( "Nrml" );
                        desc376.putEnumerated( idbaseline, idbaseline, idNrml );
                        var idotbaseline = stringIDToTypeID( "otbaseline" );
                        var idotbaseline = stringIDToTypeID( "otbaseline" );
                        var idNrml = charIDToTypeID( "Nrml" );
                        desc376.putEnumerated( idotbaseline, idotbaseline, idNrml );
                        var idstrikethrough = stringIDToTypeID( "strikethrough" );
                        var idstrikethrough = stringIDToTypeID( "strikethrough" );
                        var idstrikethroughOff = stringIDToTypeID( "strikethroughOff" );
                        desc376.putEnumerated( idstrikethrough, idstrikethrough, idstrikethroughOff );
                        var idUndl = charIDToTypeID( "Undl" );
                        var idUndl = charIDToTypeID( "Undl" );
                        var idunderlineOff = stringIDToTypeID( "underlineOff" );
                        desc376.putEnumerated( idUndl, idUndl, idunderlineOff );
                        var idunderlineOffset = stringIDToTypeID( "underlineOffset" );
                        var idPnt = charIDToTypeID( "#Pnt" );
                        desc376.putUnitDouble( idunderlineOffset, idPnt, 0.000000 );
                        var idligature = stringIDToTypeID( "ligature" );
                        desc376.putBoolean( idligature, true );
                        var idaltligature = stringIDToTypeID( "altligature" );
                        desc376.putBoolean( idaltligature, false );
                        var idcontextualLigatures = stringIDToTypeID( "contextualLigatures" );
                        desc376.putBoolean( idcontextualLigatures, false );
                        var idalternateLigatures = stringIDToTypeID( "alternateLigatures" );
                        desc376.putBoolean( idalternateLigatures, false );
                        var idoldStyle = stringIDToTypeID( "oldStyle" );
                        desc376.putBoolean( idoldStyle, false );
                        var idfractions = stringIDToTypeID( "fractions" );
                        desc376.putBoolean( idfractions, false );
                        var idordinals = stringIDToTypeID( "ordinals" );
                        desc376.putBoolean( idordinals, false );
                        var idswash = stringIDToTypeID( "swash" );
                        desc376.putBoolean( idswash, false );
                        var idtitling = stringIDToTypeID( "titling" );
                        desc376.putBoolean( idtitling, false );
                        var idconnectionForms = stringIDToTypeID( "connectionForms" );
                        desc376.putBoolean( idconnectionForms, false );
                        var idstylisticAlternates = stringIDToTypeID( "stylisticAlternates" );
                        desc376.putBoolean( idstylisticAlternates, false );
                        var idstylisticSets = stringIDToTypeID( "stylisticSets" );
                        desc376.putInteger( idstylisticSets, 0 );
                        var idornaments = stringIDToTypeID( "ornaments" );
                        desc376.putBoolean( idornaments, false );
                        var idjustificationAlternates = stringIDToTypeID( "justificationAlternates" );
                        desc376.putBoolean( idjustificationAlternates, false );
                        var idfigureStyle = stringIDToTypeID( "figureStyle" );
                        var idfigureStyle = stringIDToTypeID( "figureStyle" );
                        var idNrml = charIDToTypeID( "Nrml" );
                        desc376.putEnumerated( idfigureStyle, idfigureStyle, idNrml );
                        var idproportionalMetrics = stringIDToTypeID( "proportionalMetrics" );
                        desc376.putBoolean( idproportionalMetrics, false );
                        var idkana = stringIDToTypeID( "kana" );
                        desc376.putBoolean( idkana, false );
                        var iditalics = stringIDToTypeID( "italics" );
                        desc376.putBoolean( iditalics, false );
                        var idruby = stringIDToTypeID( "ruby" );
                        desc376.putBoolean( idruby, false );
                        var idbaselineDirection = stringIDToTypeID( "baselineDirection" );
                        var idbaselineDirection = stringIDToTypeID( "baselineDirection" );
                        var idrotated = stringIDToTypeID( "rotated" );
                        desc376.putEnumerated( idbaselineDirection, idbaselineDirection, idrotated );
                        var idtextLanguage = stringIDToTypeID( "textLanguage" );
                        var idtextLanguage = stringIDToTypeID( "textLanguage" );
                        var idenglishLanguage = stringIDToTypeID( "englishLanguage" );
                        desc376.putEnumerated( idtextLanguage, idtextLanguage, idenglishLanguage );
                        var idjapaneseAlternate = stringIDToTypeID( "japaneseAlternate" );
                        var idjapaneseAlternate = stringIDToTypeID( "japaneseAlternate" );
                        var iddefaultForm = stringIDToTypeID( "defaultForm" );
                        desc376.putEnumerated( idjapaneseAlternate, idjapaneseAlternate, iddefaultForm );
                        var idmojiZume = stringIDToTypeID( "mojiZume" );
                        desc376.putDouble( idmojiZume, 0.000000 );
                        var idgridAlignment = stringIDToTypeID( "gridAlignment" );
                        var idgridAlignment = stringIDToTypeID( "gridAlignment" );
                        var idroman = stringIDToTypeID( "roman" );
                        desc376.putEnumerated( idgridAlignment, idgridAlignment, idroman );
                        var idenableWariChu = stringIDToTypeID( "enableWariChu" );
                        desc376.putBoolean( idenableWariChu, false );
                        var idwariChuCount = stringIDToTypeID( "wariChuCount" );
                        desc376.putInteger( idwariChuCount, 2 );
                        var idwariChuLineGap = stringIDToTypeID( "wariChuLineGap" );
                        desc376.putInteger( idwariChuLineGap, 0 );
                        var idwariChuScale = stringIDToTypeID( "wariChuScale" );
                        desc376.putDouble( idwariChuScale, 0.500000 );
                        var idwariChuWidow = stringIDToTypeID( "wariChuWidow" );
                        desc376.putInteger( idwariChuWidow, 2 );
                        var idwariChuOrphan = stringIDToTypeID( "wariChuOrphan" );
                        desc376.putInteger( idwariChuOrphan, 2 );
                        var idwariChuJustification = stringIDToTypeID( "wariChuJustification" );
                        var idwariChuJustification = stringIDToTypeID( "wariChuJustification" );
                        var idwariChuAutoJustify = stringIDToTypeID( "wariChuAutoJustify" );
                        desc376.putEnumerated( idwariChuJustification, idwariChuJustification, idwariChuAutoJustify );
                        var idtcyUpDown = stringIDToTypeID( "tcyUpDown" );
                        desc376.putInteger( idtcyUpDown, 0 );
                        var idtcyLeftRight = stringIDToTypeID( "tcyLeftRight" );
                        desc376.putInteger( idtcyLeftRight, 0 );
                        var idleftAki = stringIDToTypeID( "leftAki" );
                        desc376.putDouble( idleftAki, -1.000000 );
                        var idrightAki = stringIDToTypeID( "rightAki" );
                        desc376.putDouble( idrightAki, -1.000000 );
                        var idjiDori = stringIDToTypeID( "jiDori" );
                        desc376.putInteger( idjiDori, 0 );
                        var idnoBreak = stringIDToTypeID( "noBreak" );
                        desc376.putBoolean( idnoBreak, false );
                        var idClr = charIDToTypeID( "Clr " );
                            var desc377 = new ActionDescriptor();
                            var idRd = charIDToTypeID( "Rd  " );
                            desc377.putDouble( idRd, 0.000000 );
                            var idGrn = charIDToTypeID( "Grn " );
                            desc377.putDouble( idGrn, 0.000000 );
                            var idBl = charIDToTypeID( "Bl  " );
                            desc377.putDouble( idBl, 0.000000 );
                        var idRGBC = charIDToTypeID( "RGBC" );
                        desc376.putObject( idClr, idRGBC, desc377 );
                        var idstrokeColor = stringIDToTypeID( "strokeColor" );
                            var desc378 = new ActionDescriptor();
                            var idRd = charIDToTypeID( "Rd  " );
                            desc378.putDouble( idRd, 0.000000 );
                            var idGrn = charIDToTypeID( "Grn " );
                            desc378.putDouble( idGrn, 0.000000 );
                            var idBl = charIDToTypeID( "Bl  " );
                            desc378.putDouble( idBl, 0.000000 );
                        var idRGBC = charIDToTypeID( "RGBC" );
                        desc376.putObject( idstrokeColor, idRGBC, desc378 );
                        var idFl = charIDToTypeID( "Fl  " );
                        desc376.putBoolean( idFl, true );
                        var idStrk = charIDToTypeID( "Strk" );
                        desc376.putBoolean( idStrk, false );
                        var idfillFirst = stringIDToTypeID( "fillFirst" );
                        desc376.putBoolean( idfillFirst, true );
                        var idfillOverPrint = stringIDToTypeID( "fillOverPrint" );
                        desc376.putBoolean( idfillOverPrint, false );
                        var idstrokeOverPrint = stringIDToTypeID( "strokeOverPrint" );
                        desc376.putBoolean( idstrokeOverPrint, false );
                        var idlineCap = stringIDToTypeID( "lineCap" );
                        var idlineCap = stringIDToTypeID( "lineCap" );
                        var idbuttCap = stringIDToTypeID( "buttCap" );
                        desc376.putEnumerated( idlineCap, idlineCap, idbuttCap );
                        var idlineJoin = stringIDToTypeID( "lineJoin" );
                        var idlineJoin = stringIDToTypeID( "lineJoin" );
                        var idmiterJoin = stringIDToTypeID( "miterJoin" );
                        desc376.putEnumerated( idlineJoin, idlineJoin, idmiterJoin );
                        var idlineWidth = stringIDToTypeID( "lineWidth" );
                        var idPnt = charIDToTypeID( "#Pnt" );
                        desc376.putUnitDouble( idlineWidth, idPnt, 1.000000 );
                        var idmiterLimit = stringIDToTypeID( "miterLimit" );
                        var idPnt = charIDToTypeID( "#Pnt" );
                        desc376.putUnitDouble( idmiterLimit, idPnt, 4.000000 );
                        var idlineDashoffset = stringIDToTypeID( "lineDashoffset" );
                        desc376.putDouble( idlineDashoffset, 0.000000 );
                    var idTxtS = charIDToTypeID( "TxtS" );
                    desc373.putObject( idbaseParentStyle, idTxtS, desc376 );
                var idTxtS = charIDToTypeID( "TxtS" );
                desc372.putObject( idTxtS, idTxtS, desc373 );
            var idTxtt = charIDToTypeID( "Txtt" );
            list56.putObject( idTxtt, desc372 );
        desc364.putList( idTxtt, list56 );
        var idparagraphStyleRange = stringIDToTypeID( "paragraphStyleRange" );
            var list57 = new ActionList();
                var desc379 = new ActionDescriptor();
                var idFrom = charIDToTypeID( "From" );
                desc379.putInteger( idFrom, 0 );
                var idT = charIDToTypeID( "T   " );
                desc379.putInteger( idT, 11 );
                var idparagraphStyle = stringIDToTypeID( "paragraphStyle" );
                    var desc380 = new ActionDescriptor();
                    var idstyleSheetHasParent = stringIDToTypeID( "styleSheetHasParent" );
                    desc380.putBoolean( idstyleSheetHasParent, true );
                    var idhyphenate = stringIDToTypeID( "hyphenate" );
                    desc380.putBoolean( idhyphenate, true );
                    var idburasagari = stringIDToTypeID( "burasagari" );
                    var idburasagari = stringIDToTypeID( "burasagari" );
                    var idburasagariStandard = stringIDToTypeID( "burasagariStandard" );
                    desc380.putEnumerated( idburasagari, idburasagari, idburasagariStandard );
                    var idtextEveryLineComposer = stringIDToTypeID( "textEveryLineComposer" );
                    desc380.putBoolean( idtextEveryLineComposer, true );
                var idparagraphStyle = stringIDToTypeID( "paragraphStyle" );
                desc379.putObject( idparagraphStyle, idparagraphStyle, desc380 );
            var idparagraphStyleRange = stringIDToTypeID( "paragraphStyleRange" );
            list57.putObject( idparagraphStyleRange, desc379 );
        desc364.putList( idparagraphStyleRange, list57 );
        var idkerningRange = stringIDToTypeID( "kerningRange" );
            var list58 = new ActionList();
        desc364.putList( idkerningRange, list58 );
    var idTxLr = charIDToTypeID( "TxLr" );
    desc363.putObject( idUsng, idTxLr, desc364 );
    var idLyrI = charIDToTypeID( "LyrI" );
    desc363.putInteger( idLyrI, 14 );    
executeAction( idMk, desc363, DialogModes.NO );
var idsetd = charIDToTypeID( "setd" );
    var desc9326 = new ActionDescriptor();
    var idnull = charIDToTypeID( "null" );
        var ref1123 = new ActionReference();
        var idLyr = charIDToTypeID( "Lyr " );
        var idOrdn = charIDToTypeID( "Ordn" );
        var idTrgt = charIDToTypeID( "Trgt" );
        ref1123.putEnumerated( idLyr, idOrdn, idTrgt );
    desc9326.putReference( idnull, ref1123 );
    var idT = charIDToTypeID( "T   " );
        var desc9327 = new ActionDescriptor();
        var idNm = charIDToTypeID( "Nm  " );
        desc9327.putString( idNm, """txt""" );
    var idLyr = charIDToTypeID( "Lyr " );
    desc9326.putObject( idT, idLyr, desc9327 );
executeAction( idsetd, desc9326, DialogModes.NO );
var idsetd = charIDToTypeID( "setd" );
    var desc408 = new ActionDescriptor();
    var idnull = charIDToTypeID( "null" );
        var ref59 = new ActionReference();
        var idPrpr = charIDToTypeID( "Prpr" );
        var idLefx = charIDToTypeID( "Lefx" );
        ref59.putProperty( idPrpr, idLefx );
        var idLyr = charIDToTypeID( "Lyr " );
        var idOrdn = charIDToTypeID( "Ordn" );
        var idTrgt = charIDToTypeID( "Trgt" );
        ref59.putEnumerated( idLyr, idOrdn, idTrgt );
    desc408.putReference( idnull, ref59 );
    var idT = charIDToTypeID( "T   " );
        var desc409 = new ActionDescriptor();
        var idScl = charIDToTypeID( "Scl " );
        var idPrc = charIDToTypeID( "#Prc" );
        desc409.putUnitDouble( idScl, idPrc, 416.666667 );
        var idFrFX = charIDToTypeID( "FrFX" );
            var desc410 = new ActionDescriptor();
            var idenab = charIDToTypeID( "enab" );
            desc410.putBoolean( idenab, true );
            var idpresent = stringIDToTypeID( "present" );
            desc410.putBoolean( idpresent, true );
            var idshowInDialog = stringIDToTypeID( "showInDialog" );
            desc410.putBoolean( idshowInDialog, true );
            var idStyl = charIDToTypeID( "Styl" );
            var idFStl = charIDToTypeID( "FStl" );
            var idOutF = charIDToTypeID( "OutF" );
            desc410.putEnumerated( idStyl, idFStl, idOutF );
            var idPntT = charIDToTypeID( "PntT" );
            var idFrFl = charIDToTypeID( "FrFl" );
            var idSClr = charIDToTypeID( "SClr" );
            desc410.putEnumerated( idPntT, idFrFl, idSClr );
            var idMd = charIDToTypeID( "Md  " );
            var idBlnM = charIDToTypeID( "BlnM" );
            var idNrml = charIDToTypeID( "Nrml" );
            desc410.putEnumerated( idMd, idBlnM, idNrml );
            var idOpct = charIDToTypeID( "Opct" );
            var idPrc = charIDToTypeID( "#Prc" );
            desc410.putUnitDouble( idOpct, idPrc, 100.000000 );
            var idSz = charIDToTypeID( "Sz  " );
            var idPxl = charIDToTypeID( "#Pxl" );
            desc410.putUnitDouble( idSz, idPxl, 9.000000 );
            var idClr = charIDToTypeID( "Clr " );
                var desc411 = new ActionDescriptor();
                var idRd = charIDToTypeID( "Rd  " );
                desc411.putDouble( idRd, 255.000000 );
                var idGrn = charIDToTypeID( "Grn " );
                desc411.putDouble( idGrn, 255.000000 );
                var idBl = charIDToTypeID( "Bl  " );
                desc411.putDouble( idBl, 255.000000 );
            var idRGBC = charIDToTypeID( "RGBC" );
            desc410.putObject( idClr, idRGBC, desc411 );
            var idoverprint = stringIDToTypeID( "overprint" );
            desc410.putBoolean( idoverprint, false );
        var idFrFX = charIDToTypeID( "FrFX" );
        desc409.putObject( idFrFX, idFrFX, desc410 );
    var idLefx = charIDToTypeID( "Lefx" );
    desc408.putObject( idT, idLefx, desc409 );
executeAction( idsetd, desc408, DialogModes.NO );
var idMk = charIDToTypeID( "Mk  " );
    var desc436 = new ActionDescriptor();
    var idnull = charIDToTypeID( "null" );
        var ref63 = new ActionReference();
        var idlayerSection = stringIDToTypeID( "layerSection" );
        ref63.putClass( idlayerSection );
    desc436.putReference( idnull, ref63 );
    var idFrom = charIDToTypeID( "From" );
        var ref64 = new ActionReference();
        var idLyr = charIDToTypeID( "Lyr " );
        var idOrdn = charIDToTypeID( "Ordn" );
        var idTrgt = charIDToTypeID( "Trgt" );
        ref64.putEnumerated( idLyr, idOrdn, idTrgt );
    desc436.putReference( idFrom, ref64 );
    var idlayerSectionStart = stringIDToTypeID( "layerSectionStart" );
    desc436.putInteger( idlayerSectionStart, 17 );
    var idlayerSectionEnd = stringIDToTypeID( "layerSectionEnd" );
    desc436.putInteger( idlayerSectionEnd, 18 );
    var idNm = charIDToTypeID( "Nm  " );
    desc436.putString( idNm, """Group 1""" );
executeAction( idMk, desc436, DialogModes.NO );
// =======================================================
var idsetd = charIDToTypeID( "setd" );
    var desc439 = new ActionDescriptor();
    var idnull = charIDToTypeID( "null" );
        var ref65 = new ActionReference();
        var idPrpr = charIDToTypeID( "Prpr" );
        var idLefx = charIDToTypeID( "Lefx" );
        ref65.putProperty( idPrpr, idLefx );
        var idLyr = charIDToTypeID( "Lyr " );
        var idOrdn = charIDToTypeID( "Ordn" );
        var idTrgt = charIDToTypeID( "Trgt" );
        ref65.putEnumerated( idLyr, idOrdn, idTrgt );
    desc439.putReference( idnull, ref65 );
    var idT = charIDToTypeID( "T   " );
        var desc440 = new ActionDescriptor();
        var idScl = charIDToTypeID( "Scl " );
        var idPrc = charIDToTypeID( "#Prc" );
        desc440.putUnitDouble( idScl, idPrc, 416.666667 );
        var iddropShadowMulti = stringIDToTypeID( "dropShadowMulti" );
            var list71 = new ActionList();
                var desc441 = new ActionDescriptor();
                var idenab = charIDToTypeID( "enab" );
                desc441.putBoolean( idenab, true );
                var idpresent = stringIDToTypeID( "present" );
                desc441.putBoolean( idpresent, true );
                var idshowInDialog = stringIDToTypeID( "showInDialog" );
                desc441.putBoolean( idshowInDialog, true );
                var idMd = charIDToTypeID( "Md  " );
                var idBlnM = charIDToTypeID( "BlnM" );
                var idNrml = charIDToTypeID( "Nrml" );
                desc441.putEnumerated( idMd, idBlnM, idNrml );
                var idClr = charIDToTypeID( "Clr " );
                    var desc442 = new ActionDescriptor();
                    var idRd = charIDToTypeID( "Rd  " );
                    desc442.putDouble( idRd, 215.000002 );
                    var idGrn = charIDToTypeID( "Grn " );
                    desc442.putDouble( idGrn, 215.000002 );
                    var idBl = charIDToTypeID( "Bl  " );
                    desc442.putDouble( idBl, 215.000002 );
                var idRGBC = charIDToTypeID( "RGBC" );
                desc441.putObject( idClr, idRGBC, desc442 );
                var idOpct = charIDToTypeID( "Opct" );
                var idPrc = charIDToTypeID( "#Prc" );
                desc441.putUnitDouble( idOpct, idPrc, 100.000000 );
                var iduglg = charIDToTypeID( "uglg" );
                desc441.putBoolean( iduglg, true );
                var idlagl = charIDToTypeID( "lagl" );
                var idAng = charIDToTypeID( "#Ang" );
                desc441.putUnitDouble( idlagl, idAng, 180.000000 );
                var idDstn = charIDToTypeID( "Dstn" );
                var idPxl = charIDToTypeID( "#Pxl" );
                desc441.putUnitDouble( idDstn, idPxl, 2.000000 );
                var idCkmt = charIDToTypeID( "Ckmt" );
                var idPxl = charIDToTypeID( "#Pxl" );
                desc441.putUnitDouble( idCkmt, idPxl, 0.000000 );
                var idblur = charIDToTypeID( "blur" );
                var idPxl = charIDToTypeID( "#Pxl" );
                desc441.putUnitDouble( idblur, idPxl, 0.000000 );
                var idNose = charIDToTypeID( "Nose" );
                var idPrc = charIDToTypeID( "#Prc" );
                desc441.putUnitDouble( idNose, idPrc, 0.000000 );
                var idAntA = charIDToTypeID( "AntA" );
                desc441.putBoolean( idAntA, true );
                var idTrnS = charIDToTypeID( "TrnS" );
                    var desc443 = new ActionDescriptor();
                    var idNm = charIDToTypeID( "Nm  " );
                    desc443.putString( idNm, """Linear""" );
                var idShpC = charIDToTypeID( "ShpC" );
                desc441.putObject( idTrnS, idShpC, desc443 );
                var idlayerConceals = stringIDToTypeID( "layerConceals" );
                desc441.putBoolean( idlayerConceals, true );
            var idDrSh = charIDToTypeID( "DrSh" );
            list71.putObject( idDrSh, desc441 );
                var desc444 = new ActionDescriptor();
                var idenab = charIDToTypeID( "enab" );
                desc444.putBoolean( idenab, true );
                var idpresent = stringIDToTypeID( "present" );
                desc444.putBoolean( idpresent, true );
                var idshowInDialog = stringIDToTypeID( "showInDialog" );
                desc444.putBoolean( idshowInDialog, true );
                var idMd = charIDToTypeID( "Md  " );
                var idBlnM = charIDToTypeID( "BlnM" );
                var idNrml = charIDToTypeID( "Nrml" );
                desc444.putEnumerated( idMd, idBlnM, idNrml );
                var idClr = charIDToTypeID( "Clr " );
                    var desc445 = new ActionDescriptor();
                    var idRd = charIDToTypeID( "Rd  " );
                    desc445.putDouble( idRd, 201.000003 );
                    var idGrn = charIDToTypeID( "Grn " );
                    desc445.putDouble( idGrn, 201.000003 );
                    var idBl = charIDToTypeID( "Bl  " );
                    desc445.putDouble( idBl, 201.000003 );
                var idRGBC = charIDToTypeID( "RGBC" );
                desc444.putObject( idClr, idRGBC, desc445 );
                var idOpct = charIDToTypeID( "Opct" );
                var idPrc = charIDToTypeID( "#Prc" );
                desc444.putUnitDouble( idOpct, idPrc, 100.000000 );
                var iduglg = charIDToTypeID( "uglg" );
                desc444.putBoolean( iduglg, true );
                var idlagl = charIDToTypeID( "lagl" );
                var idAng = charIDToTypeID( "#Ang" );
                desc444.putUnitDouble( idlagl, idAng, 180.000000 );
                var idDstn = charIDToTypeID( "Dstn" );
                var idPxl = charIDToTypeID( "#Pxl" );
                desc444.putUnitDouble( idDstn, idPxl, 4.000000 );
                var idCkmt = charIDToTypeID( "Ckmt" );
                var idPxl = charIDToTypeID( "#Pxl" );
                desc444.putUnitDouble( idCkmt, idPxl, 0.000000 );
                var idblur = charIDToTypeID( "blur" );
                var idPxl = charIDToTypeID( "#Pxl" );
                desc444.putUnitDouble( idblur, idPxl, 0.000000 );
                var idNose = charIDToTypeID( "Nose" );
                var idPrc = charIDToTypeID( "#Prc" );
                desc444.putUnitDouble( idNose, idPrc, 0.000000 );
                var idAntA = charIDToTypeID( "AntA" );
                desc444.putBoolean( idAntA, true );
                var idTrnS = charIDToTypeID( "TrnS" );
                    var desc446 = new ActionDescriptor();
                    var idNm = charIDToTypeID( "Nm  " );
                    desc446.putString( idNm, """Linear""" );
                var idShpC = charIDToTypeID( "ShpC" );
                desc444.putObject( idTrnS, idShpC, desc446 );
                var idlayerConceals = stringIDToTypeID( "layerConceals" );
                desc444.putBoolean( idlayerConceals, true );
            var idDrSh = charIDToTypeID( "DrSh" );
            list71.putObject( idDrSh, desc444 );
                var desc447 = new ActionDescriptor();
                var idenab = charIDToTypeID( "enab" );
                desc447.putBoolean( idenab, true );
                var idpresent = stringIDToTypeID( "present" );
                desc447.putBoolean( idpresent, true );
                var idshowInDialog = stringIDToTypeID( "showInDialog" );
                desc447.putBoolean( idshowInDialog, true );
                var idMd = charIDToTypeID( "Md  " );
                var idBlnM = charIDToTypeID( "BlnM" );
                var idNrml = charIDToTypeID( "Nrml" );
                desc447.putEnumerated( idMd, idBlnM, idNrml );
                var idClr = charIDToTypeID( "Clr " );
                    var desc448 = new ActionDescriptor();
                    var idRd = charIDToTypeID( "Rd  " );
                    desc448.putDouble( idRd, 186.000004 );
                    var idGrn = charIDToTypeID( "Grn " );
                    desc448.putDouble( idGrn, 186.000004 );
                    var idBl = charIDToTypeID( "Bl  " );
                    desc448.putDouble( idBl, 186.000004 );
                var idRGBC = charIDToTypeID( "RGBC" );
                desc447.putObject( idClr, idRGBC, desc448 );
                var idOpct = charIDToTypeID( "Opct" );
                var idPrc = charIDToTypeID( "#Prc" );
                desc447.putUnitDouble( idOpct, idPrc, 100.000000 );
                var iduglg = charIDToTypeID( "uglg" );
                desc447.putBoolean( iduglg, true );
                var idlagl = charIDToTypeID( "lagl" );
                var idAng = charIDToTypeID( "#Ang" );
                desc447.putUnitDouble( idlagl, idAng, 180.000000 );
                var idDstn = charIDToTypeID( "Dstn" );
                var idPxl = charIDToTypeID( "#Pxl" );
                desc447.putUnitDouble( idDstn, idPxl, 6.000000 );
                var idCkmt = charIDToTypeID( "Ckmt" );
                var idPxl = charIDToTypeID( "#Pxl" );
                desc447.putUnitDouble( idCkmt, idPxl, 0.000000 );
                var idblur = charIDToTypeID( "blur" );
                var idPxl = charIDToTypeID( "#Pxl" );
                desc447.putUnitDouble( idblur, idPxl, 0.000000 );
                var idNose = charIDToTypeID( "Nose" );
                var idPrc = charIDToTypeID( "#Prc" );
                desc447.putUnitDouble( idNose, idPrc, 0.000000 );
                var idAntA = charIDToTypeID( "AntA" );
                desc447.putBoolean( idAntA, true );
                var idTrnS = charIDToTypeID( "TrnS" );
                    var desc449 = new ActionDescriptor();
                    var idNm = charIDToTypeID( "Nm  " );
                    desc449.putString( idNm, """Linear""" );
                var idShpC = charIDToTypeID( "ShpC" );
                desc447.putObject( idTrnS, idShpC, desc449 );
                var idlayerConceals = stringIDToTypeID( "layerConceals" );
                desc447.putBoolean( idlayerConceals, true );
            var idDrSh = charIDToTypeID( "DrSh" );
            list71.putObject( idDrSh, desc447 );
                var desc450 = new ActionDescriptor();
                var idenab = charIDToTypeID( "enab" );
                desc450.putBoolean( idenab, true );
                var idpresent = stringIDToTypeID( "present" );
                desc450.putBoolean( idpresent, true );
                var idshowInDialog = stringIDToTypeID( "showInDialog" );
                desc450.putBoolean( idshowInDialog, true );
                var idMd = charIDToTypeID( "Md  " );
                var idBlnM = charIDToTypeID( "BlnM" );
                var idNrml = charIDToTypeID( "Nrml" );
                desc450.putEnumerated( idMd, idBlnM, idNrml );
                var idClr = charIDToTypeID( "Clr " );
                    var desc451 = new ActionDescriptor();
                    var idRd = charIDToTypeID( "Rd  " );
                    desc451.putDouble( idRd, 160.000006 );
                    var idGrn = charIDToTypeID( "Grn " );
                    desc451.putDouble( idGrn, 160.000006 );
                    var idBl = charIDToTypeID( "Bl  " );
                    desc451.putDouble( idBl, 160.000006 );
                var idRGBC = charIDToTypeID( "RGBC" );
                desc450.putObject( idClr, idRGBC, desc451 );
                var idOpct = charIDToTypeID( "Opct" );
                var idPrc = charIDToTypeID( "#Prc" );
                desc450.putUnitDouble( idOpct, idPrc, 100.000000 );
                var iduglg = charIDToTypeID( "uglg" );
                desc450.putBoolean( iduglg, true );
                var idlagl = charIDToTypeID( "lagl" );
                var idAng = charIDToTypeID( "#Ang" );
                desc450.putUnitDouble( idlagl, idAng, 180.000000 );
                var idDstn = charIDToTypeID( "Dstn" );
                var idPxl = charIDToTypeID( "#Pxl" );
                desc450.putUnitDouble( idDstn, idPxl, 8.000000 );
                var idCkmt = charIDToTypeID( "Ckmt" );
                var idPxl = charIDToTypeID( "#Pxl" );
                desc450.putUnitDouble( idCkmt, idPxl, 0.000000 );
                var idblur = charIDToTypeID( "blur" );
                var idPxl = charIDToTypeID( "#Pxl" );
                desc450.putUnitDouble( idblur, idPxl, 0.000000 );
                var idNose = charIDToTypeID( "Nose" );
                var idPrc = charIDToTypeID( "#Prc" );
                desc450.putUnitDouble( idNose, idPrc, 0.000000 );
                var idAntA = charIDToTypeID( "AntA" );
                desc450.putBoolean( idAntA, true );
                var idTrnS = charIDToTypeID( "TrnS" );
                    var desc452 = new ActionDescriptor();
                    var idNm = charIDToTypeID( "Nm  " );
                    desc452.putString( idNm, """Linear""" );
                var idShpC = charIDToTypeID( "ShpC" );
                desc450.putObject( idTrnS, idShpC, desc452 );
                var idlayerConceals = stringIDToTypeID( "layerConceals" );
                desc450.putBoolean( idlayerConceals, true );
            var idDrSh = charIDToTypeID( "DrSh" );
            list71.putObject( idDrSh, desc450 );
                var desc453 = new ActionDescriptor();
                var idenab = charIDToTypeID( "enab" );
                desc453.putBoolean( idenab, true );
                var idpresent = stringIDToTypeID( "present" );
                desc453.putBoolean( idpresent, true );
                var idshowInDialog = stringIDToTypeID( "showInDialog" );
                desc453.putBoolean( idshowInDialog, true );
                var idMd = charIDToTypeID( "Md  " );
                var idBlnM = charIDToTypeID( "BlnM" );
                var idNrml = charIDToTypeID( "Nrml" );
                desc453.putEnumerated( idMd, idBlnM, idNrml );
                var idClr = charIDToTypeID( "Clr " );
                    var desc454 = new ActionDescriptor();
                    var idRd = charIDToTypeID( "Rd  " );
                    desc454.putDouble( idRd, 143.000007 );
                    var idGrn = charIDToTypeID( "Grn " );
                    desc454.putDouble( idGrn, 142.435798 );
                    var idBl = charIDToTypeID( "Bl  " );
                    desc454.putDouble( idBl, 142.435798 );
                var idRGBC = charIDToTypeID( "RGBC" );
                desc453.putObject( idClr, idRGBC, desc454 );
                var idOpct = charIDToTypeID( "Opct" );
                var idPrc = charIDToTypeID( "#Prc" );
                desc453.putUnitDouble( idOpct, idPrc, 100.000000 );
                var iduglg = charIDToTypeID( "uglg" );
                desc453.putBoolean( iduglg, true );
                var idlagl = charIDToTypeID( "lagl" );
                var idAng = charIDToTypeID( "#Ang" );
                desc453.putUnitDouble( idlagl, idAng, 180.000000 );
                var idDstn = charIDToTypeID( "Dstn" );
                var idPxl = charIDToTypeID( "#Pxl" );
                desc453.putUnitDouble( idDstn, idPxl, 10.000000 );
                var idCkmt = charIDToTypeID( "Ckmt" );
                var idPxl = charIDToTypeID( "#Pxl" );
                desc453.putUnitDouble( idCkmt, idPxl, 0.000000 );
                var idblur = charIDToTypeID( "blur" );
                var idPxl = charIDToTypeID( "#Pxl" );
                desc453.putUnitDouble( idblur, idPxl, 0.000000 );
                var idNose = charIDToTypeID( "Nose" );
                var idPrc = charIDToTypeID( "#Prc" );
                desc453.putUnitDouble( idNose, idPrc, 0.000000 );
                var idAntA = charIDToTypeID( "AntA" );
                desc453.putBoolean( idAntA, true );
                var idTrnS = charIDToTypeID( "TrnS" );
                    var desc455 = new ActionDescriptor();
                    var idNm = charIDToTypeID( "Nm  " );
                    desc455.putString( idNm, """Linear""" );
                var idShpC = charIDToTypeID( "ShpC" );
                desc453.putObject( idTrnS, idShpC, desc455 );
                var idlayerConceals = stringIDToTypeID( "layerConceals" );
                desc453.putBoolean( idlayerConceals, true );
            var idDrSh = charIDToTypeID( "DrSh" );
            list71.putObject( idDrSh, desc453 );
                var desc456 = new ActionDescriptor();
                var idenab = charIDToTypeID( "enab" );
                desc456.putBoolean( idenab, true );
                var idpresent = stringIDToTypeID( "present" );
                desc456.putBoolean( idpresent, true );
                var idshowInDialog = stringIDToTypeID( "showInDialog" );
                desc456.putBoolean( idshowInDialog, true );
                var idMd = charIDToTypeID( "Md  " );
                var idBlnM = charIDToTypeID( "BlnM" );
                var idNrml = charIDToTypeID( "Nrml" );
                desc456.putEnumerated( idMd, idBlnM, idNrml );
                var idClr = charIDToTypeID( "Clr " );
                    var desc457 = new ActionDescriptor();
                    var idRd = charIDToTypeID( "Rd  " );
                    desc457.putDouble( idRd, 141.000007 );
                    var idGrn = charIDToTypeID( "Grn " );
                    desc457.putDouble( idGrn, 141.000007 );
                    var idBl = charIDToTypeID( "Bl  " );
                    desc457.putDouble( idBl, 141.000007 );
                var idRGBC = charIDToTypeID( "RGBC" );
                desc456.putObject( idClr, idRGBC, desc457 );
                var idOpct = charIDToTypeID( "Opct" );
                var idPrc = charIDToTypeID( "#Prc" );
                desc456.putUnitDouble( idOpct, idPrc, 100.000000 );
                var iduglg = charIDToTypeID( "uglg" );
                desc456.putBoolean( iduglg, true );
                var idlagl = charIDToTypeID( "lagl" );
                var idAng = charIDToTypeID( "#Ang" );
                desc456.putUnitDouble( idlagl, idAng, 180.000000 );
                var idDstn = charIDToTypeID( "Dstn" );
                var idPxl = charIDToTypeID( "#Pxl" );
                desc456.putUnitDouble( idDstn, idPxl, 12.000000 );
                var idCkmt = charIDToTypeID( "Ckmt" );
                var idPxl = charIDToTypeID( "#Pxl" );
                desc456.putUnitDouble( idCkmt, idPxl, 0.000000 );
                var idblur = charIDToTypeID( "blur" );
                var idPxl = charIDToTypeID( "#Pxl" );
                desc456.putUnitDouble( idblur, idPxl, 0.000000 );
                var idNose = charIDToTypeID( "Nose" );
                var idPrc = charIDToTypeID( "#Prc" );
                desc456.putUnitDouble( idNose, idPrc, 0.000000 );
                var idAntA = charIDToTypeID( "AntA" );
                desc456.putBoolean( idAntA, true );
                var idTrnS = charIDToTypeID( "TrnS" );
                    var desc458 = new ActionDescriptor();
                    var idNm = charIDToTypeID( "Nm  " );
                    desc458.putString( idNm, """Linear""" );
                var idShpC = charIDToTypeID( "ShpC" );
                desc456.putObject( idTrnS, idShpC, desc458 );
                var idlayerConceals = stringIDToTypeID( "layerConceals" );
                desc456.putBoolean( idlayerConceals, true );
            var idDrSh = charIDToTypeID( "DrSh" );
            list71.putObject( idDrSh, desc456 );
                var desc459 = new ActionDescriptor();
                var idenab = charIDToTypeID( "enab" );
                desc459.putBoolean( idenab, true );
                var idpresent = stringIDToTypeID( "present" );
                desc459.putBoolean( idpresent, true );
                var idshowInDialog = stringIDToTypeID( "showInDialog" );
                desc459.putBoolean( idshowInDialog, true );
                var idMd = charIDToTypeID( "Md  " );
                var idBlnM = charIDToTypeID( "BlnM" );
                var idNrml = charIDToTypeID( "Nrml" );
                desc459.putEnumerated( idMd, idBlnM, idNrml );
                var idClr = charIDToTypeID( "Clr " );
                    var desc460 = new ActionDescriptor();
                    var idRd = charIDToTypeID( "Rd  " );
                    desc460.putDouble( idRd, 126.000000 );
                    var idGrn = charIDToTypeID( "Grn " );
                    desc460.putDouble( idGrn, 126.000000 );
                    var idBl = charIDToTypeID( "Bl  " );
                    desc460.putDouble( idBl, 126.000000 );
                var idRGBC = charIDToTypeID( "RGBC" );
                desc459.putObject( idClr, idRGBC, desc460 );
                var idOpct = charIDToTypeID( "Opct" );
                var idPrc = charIDToTypeID( "#Prc" );
                desc459.putUnitDouble( idOpct, idPrc, 100.000000 );
                var iduglg = charIDToTypeID( "uglg" );
                desc459.putBoolean( iduglg, true );
                var idlagl = charIDToTypeID( "lagl" );
                var idAng = charIDToTypeID( "#Ang" );
                desc459.putUnitDouble( idlagl, idAng, 180.000000 );
                var idDstn = charIDToTypeID( "Dstn" );
                var idPxl = charIDToTypeID( "#Pxl" );
                desc459.putUnitDouble( idDstn, idPxl, 14.000000 );
                var idCkmt = charIDToTypeID( "Ckmt" );
                var idPxl = charIDToTypeID( "#Pxl" );
                desc459.putUnitDouble( idCkmt, idPxl, 0.000000 );
                var idblur = charIDToTypeID( "blur" );
                var idPxl = charIDToTypeID( "#Pxl" );
                desc459.putUnitDouble( idblur, idPxl, 0.000000 );
                var idNose = charIDToTypeID( "Nose" );
                var idPrc = charIDToTypeID( "#Prc" );
                desc459.putUnitDouble( idNose, idPrc, 0.000000 );
                var idAntA = charIDToTypeID( "AntA" );
                desc459.putBoolean( idAntA, true );
                var idTrnS = charIDToTypeID( "TrnS" );
                    var desc461 = new ActionDescriptor();
                    var idNm = charIDToTypeID( "Nm  " );
                    desc461.putString( idNm, """Linear""" );
                var idShpC = charIDToTypeID( "ShpC" );
                desc459.putObject( idTrnS, idShpC, desc461 );
                var idlayerConceals = stringIDToTypeID( "layerConceals" );
                desc459.putBoolean( idlayerConceals, true );
            var idDrSh = charIDToTypeID( "DrSh" );
            list71.putObject( idDrSh, desc459 );
                var desc462 = new ActionDescriptor();
                var idenab = charIDToTypeID( "enab" );
                desc462.putBoolean( idenab, true );
                var idpresent = stringIDToTypeID( "present" );
                desc462.putBoolean( idpresent, true );
                var idshowInDialog = stringIDToTypeID( "showInDialog" );
                desc462.putBoolean( idshowInDialog, true );
                var idMd = charIDToTypeID( "Md  " );
                var idBlnM = charIDToTypeID( "BlnM" );
                var idNrml = charIDToTypeID( "Nrml" );
                desc462.putEnumerated( idMd, idBlnM, idNrml );
                var idClr = charIDToTypeID( "Clr " );
                    var desc463 = new ActionDescriptor();
                    var idRd = charIDToTypeID( "Rd  " );
                    desc463.putDouble( idRd, 100.000002 );
                    var idGrn = charIDToTypeID( "Grn " );
                    desc463.putDouble( idGrn, 100.000002 );
                    var idBl = charIDToTypeID( "Bl  " );
                    desc463.putDouble( idBl, 100.000002 );
                var idRGBC = charIDToTypeID( "RGBC" );
                desc462.putObject( idClr, idRGBC, desc463 );
                var idOpct = charIDToTypeID( "Opct" );
                var idPrc = charIDToTypeID( "#Prc" );
                desc462.putUnitDouble( idOpct, idPrc, 100.000000 );
                var iduglg = charIDToTypeID( "uglg" );
                desc462.putBoolean( iduglg, true );
                var idlagl = charIDToTypeID( "lagl" );
                var idAng = charIDToTypeID( "#Ang" );
                desc462.putUnitDouble( idlagl, idAng, 180.000000 );
                var idDstn = charIDToTypeID( "Dstn" );
                var idPxl = charIDToTypeID( "#Pxl" );
                desc462.putUnitDouble( idDstn, idPxl, 16.000000 );
                var idCkmt = charIDToTypeID( "Ckmt" );
                var idPxl = charIDToTypeID( "#Pxl" );
                desc462.putUnitDouble( idCkmt, idPxl, 0.000000 );
                var idblur = charIDToTypeID( "blur" );
                var idPxl = charIDToTypeID( "#Pxl" );
                desc462.putUnitDouble( idblur, idPxl, 0.000000 );
                var idNose = charIDToTypeID( "Nose" );
                var idPrc = charIDToTypeID( "#Prc" );
                desc462.putUnitDouble( idNose, idPrc, 0.000000 );
                var idAntA = charIDToTypeID( "AntA" );
                desc462.putBoolean( idAntA, true );
                var idTrnS = charIDToTypeID( "TrnS" );
                    var desc464 = new ActionDescriptor();
                    var idNm = charIDToTypeID( "Nm  " );
                    desc464.putString( idNm, """Linear""" );
                var idShpC = charIDToTypeID( "ShpC" );
                desc462.putObject( idTrnS, idShpC, desc464 );
                var idlayerConceals = stringIDToTypeID( "layerConceals" );
                desc462.putBoolean( idlayerConceals, true );
            var idDrSh = charIDToTypeID( "DrSh" );
            list71.putObject( idDrSh, desc462 );
                var desc465 = new ActionDescriptor();
                var idenab = charIDToTypeID( "enab" );
                desc465.putBoolean( idenab, true );
                var idpresent = stringIDToTypeID( "present" );
                desc465.putBoolean( idpresent, true );
                var idshowInDialog = stringIDToTypeID( "showInDialog" );
                desc465.putBoolean( idshowInDialog, true );
                var idMd = charIDToTypeID( "Md  " );
                var idBlnM = charIDToTypeID( "BlnM" );
                var idNrml = charIDToTypeID( "Nrml" );
                desc465.putEnumerated( idMd, idBlnM, idNrml );
                var idClr = charIDToTypeID( "Clr " );
                    var desc466 = new ActionDescriptor();
                    var idRd = charIDToTypeID( "Rd  " );
                    desc466.putDouble( idRd, 68.000004 );
                    var idGrn = charIDToTypeID( "Grn " );
                    desc466.putDouble( idGrn, 68.000004 );
                    var idBl = charIDToTypeID( "Bl  " );
                    desc466.putDouble( idBl, 68.000004 );
                var idRGBC = charIDToTypeID( "RGBC" );
                desc465.putObject( idClr, idRGBC, desc466 );
                var idOpct = charIDToTypeID( "Opct" );
                var idPrc = charIDToTypeID( "#Prc" );
                desc465.putUnitDouble( idOpct, idPrc, 100.000000 );
                var iduglg = charIDToTypeID( "uglg" );
                desc465.putBoolean( iduglg, true );
                var idlagl = charIDToTypeID( "lagl" );
                var idAng = charIDToTypeID( "#Ang" );
                desc465.putUnitDouble( idlagl, idAng, 180.000000 );
                var idDstn = charIDToTypeID( "Dstn" );
                var idPxl = charIDToTypeID( "#Pxl" );
                desc465.putUnitDouble( idDstn, idPxl, 18.000000 );
                var idCkmt = charIDToTypeID( "Ckmt" );
                var idPxl = charIDToTypeID( "#Pxl" );
                desc465.putUnitDouble( idCkmt, idPxl, 0.000000 );
                var idblur = charIDToTypeID( "blur" );
                var idPxl = charIDToTypeID( "#Pxl" );
                desc465.putUnitDouble( idblur, idPxl, 0.000000 );
                var idNose = charIDToTypeID( "Nose" );
                var idPrc = charIDToTypeID( "#Prc" );
                desc465.putUnitDouble( idNose, idPrc, 0.000000 );
                var idAntA = charIDToTypeID( "AntA" );
                desc465.putBoolean( idAntA, true );
                var idTrnS = charIDToTypeID( "TrnS" );
                    var desc467 = new ActionDescriptor();
                    var idNm = charIDToTypeID( "Nm  " );
                    desc467.putString( idNm, """Linear""" );
                var idShpC = charIDToTypeID( "ShpC" );
                desc465.putObject( idTrnS, idShpC, desc467 );
                var idlayerConceals = stringIDToTypeID( "layerConceals" );
                desc465.putBoolean( idlayerConceals, true );
            var idDrSh = charIDToTypeID( "DrSh" );
            list71.putObject( idDrSh, desc465 );
                var desc468 = new ActionDescriptor();
                var idenab = charIDToTypeID( "enab" );
                desc468.putBoolean( idenab, true );
                var idpresent = stringIDToTypeID( "present" );
                desc468.putBoolean( idpresent, true );
                var idshowInDialog = stringIDToTypeID( "showInDialog" );
                desc468.putBoolean( idshowInDialog, true );
                var idMd = charIDToTypeID( "Md  " );
                var idBlnM = charIDToTypeID( "BlnM" );
                var idMltp = charIDToTypeID( "Mltp" );
                desc468.putEnumerated( idMd, idBlnM, idMltp );
                var idClr = charIDToTypeID( "Clr " );
                    var desc469 = new ActionDescriptor();
                    var idRd = charIDToTypeID( "Rd  " );
                    desc469.putDouble( idRd, 0.000000 );
                    var idGrn = charIDToTypeID( "Grn " );
                    desc469.putDouble( idGrn, 0.000000 );
                    var idBl = charIDToTypeID( "Bl  " );
                    desc469.putDouble( idBl, 0.000000 );
                var idRGBC = charIDToTypeID( "RGBC" );
                desc468.putObject( idClr, idRGBC, desc469 );
                var idOpct = charIDToTypeID( "Opct" );
                var idPrc = charIDToTypeID( "#Prc" );
                desc468.putUnitDouble( idOpct, idPrc, 65.000000 );
                var iduglg = charIDToTypeID( "uglg" );
                desc468.putBoolean( iduglg, true );
                var idlagl = charIDToTypeID( "lagl" );
                var idAng = charIDToTypeID( "#Ang" );
                desc468.putUnitDouble( idlagl, idAng, 180.000000 );
                var idDstn = charIDToTypeID( "Dstn" );
                var idPxl = charIDToTypeID( "#Pxl" );
                desc468.putUnitDouble( idDstn, idPxl, 17.000000 );
                var idCkmt = charIDToTypeID( "Ckmt" );
                var idPxl = charIDToTypeID( "#Pxl" );
                desc468.putUnitDouble( idCkmt, idPxl, 0.000000 );
                var idblur = charIDToTypeID( "blur" );
                var idPxl = charIDToTypeID( "#Pxl" );
                desc468.putUnitDouble( idblur, idPxl, 49.000000 );
                var idNose = charIDToTypeID( "Nose" );
                var idPrc = charIDToTypeID( "#Prc" );
                desc468.putUnitDouble( idNose, idPrc, 0.000000 );
                var idAntA = charIDToTypeID( "AntA" );
                desc468.putBoolean( idAntA, true );
                var idTrnS = charIDToTypeID( "TrnS" );
                    var desc470 = new ActionDescriptor();
                    var idNm = charIDToTypeID( "Nm  " );
                    desc470.putString( idNm, """Linear""" );
                var idShpC = charIDToTypeID( "ShpC" );
                desc468.putObject( idTrnS, idShpC, desc470 );
                var idlayerConceals = stringIDToTypeID( "layerConceals" );
                desc468.putBoolean( idlayerConceals, true );
            var idDrSh = charIDToTypeID( "DrSh" );
            list71.putObject( idDrSh, desc468 );
        desc440.putList( iddropShadowMulti, list71 );
    var idLefx = charIDToTypeID( "Lefx" );
    desc439.putObject( idT, idLefx, desc440 );
executeAction( idsetd, desc439, DialogModes.NO );
var idnewPlacedLayer = stringIDToTypeID( "newPlacedLayer" );
executeAction( idnewPlacedLayer, undefined, DialogModes.NO );

    
}
